# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 11 * * *'  # 每10分钟触发一次

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
#uses 关键字指定此步骤将运行 actions/checkout 操作的 v3。 这是一个将存储
#库签出到运行器上的操作，允许您对代码（如生成和测试工具）运行脚本或其他操
#作。 每当工作流程将针对存储库的代码运行时，都应使用签出操作。
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.12
    - name: requirements
      run: |
        python -m pip install --upgrade pip
        pip3 install -r requirements.txt
       # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi 
    - name: build
      run: |
        python3 ./飞书天气机器人.py 
env: 
  #设置secrets的环境变量
  WEATHER_URL: ${{ secrets.WEATHER_URL }}
  WEBHOOK: ${{ secrets.WEBHOOK }}
